# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailOpen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('mail', models.CharField(max_length=100, verbose_name='mail')),
            ],
            options={
                'verbose_name_plural': 'MailOpen',
                'verbose_name': 'MailOpen',
            },
        ),
    ]
